apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rohitwebs1
  name: rohitwebs1
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: rohitwebs1
  type: NodePort
status:
  loadBalancer: {}
